### ISSUE TITLE
Build fails in Angular5: index.ts missing from Typescript compilation

### ISSUE THREAD

**Issue by lehtiniemi** [shubhi1407/ng2-component-spinner#3]
When I try to compile a project with this module in Angular5, the build fails with the following error:

ERROR in ./node_modules/ng2-component-spinner/index.ts
Module build failed: Error: .\node_modules\ng2-component-spinner\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (.\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (.\nordic-sounds\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

It works well when using ng serve, though, this is only in build.

**Comment by shayts** [comment]
I have the same problem.
